name: db-sandbox
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: db_sandbox
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_sandbox:/var/lib/mysql
# Names our volume
volumes:
      db_sandbox: